#################################################################
#  module path config
#################################################################
# This file contains all path of rnaseq analysis and
# needed softwares in rnaseq analysis.
# 1. You could add these software to your PATH.
# 2. Copy this file to '~/.multiqc_config.yaml' or
# '<working directory>/multiqc_config.yaml' and
# add absolute path to the softwares.
#################################################################

########################################
# module names                         #
########################################

module_name:
  test:
  fastqc:
    - 'run_fastqc'
    - 'fastqc_summary'
    - 'gc_plot'
    - 'reads_quality_plot'
  star_mapping:
    - 'run_star'
    - 'get_bam_file'
    - 'star_mapping_summary'
  quant:
    - 'run_kallisto'
    - 'kallisto_to_matrix'
    - 'run_diff'
    - 'get_excel_table'
    - 'quant_report_data'
  enrich:
    - 'run_goseq'
    - 'run_kobas'
    - 'run_pathway'
    - 'run_enrich_barplot'

########################################
# config directory of each module      #
########################################
module_dir:
  test:
    main: 'test_dir'
    logs: 'test_dir/logs'
  fastqc:
    main: 'fastqc'
    logs: 'fastqc/logs'
    fastqc: 'fastqc/fastqc_results'
    gc: 'fastqc/gc_plot'
    reads_quality: 'fastqc/reads_quality_plot'
  star_mapping:
    main: 'mapping'
    bam: 'mapping/bam_dir'
    map: 'mapping/mapping_dir'
    logs: 'mapping/logs'
  assembly:
    main: 'assembly'
    assemble: 'assembly/assemble'
    merge: 'assembly/merge'
    logs: 'assembly/logs'
  quick_enrich: &quick_enrich
    main: 'enrichment'
    go: 'enrichment/go'
    kegg: 'enrichment/kegg'
    blast: 'enrichment/blasttab'
    logs: 'enrichment/logs'
  quant:
    main: 'quantification'
    diff: 'quantification/differential_analysis'
    exp: 'quantification/expression_summary'
    kallisto: 'quantification/kallisto'
    logs: 'quantification/logs'
  enrich:
    <<: *quick_enrich
  _module_summary:
    logs: 'logs'
    result: 'result/analysis_result'
    report: 'result/analysis_report'
    report_data: 'result/analysis_report/report_data'
  result:
    main: 'result'
    result: 'result/analysis_result'
    report: 'result/analysis_report'
    report_data: 'result/analysis_report/report_data'
  qc:
    main: 'qc'
    logs: 'qc/logs'
    data: 'qc/qc_data'

########################################
# config software path                 #
########################################
module_software:
  fastqc: 'fastqc'
  Rscript: 'Rscript'
  star_mapping: 'STAR'
  kallisto: 'kallisto'
  stringtie: 'stringtie'
  gffread: 'gffread'
  trimmomatic: '/public/software/Trimmomatic/Trimmomatic-0.36/trimmomatic-0.36.jar'

########################################
# config command line for each module  #
########################################
module_cmd:
  fastqc:
    run_trimmomatic: ''
    run_fastqc: '{t.fastqc_bin}
                 {t.clean_dir}/{t.sample}_1.{t.fq_suffix} {t.clean_dir}/{t.sample}_2.{t.fq_suffix}
                 --extract
                 -o {t.proj_dir}/{t.fastqc_dir}'
    fastqc_summary: 'python {t._script} {t.sample_inf} {t.proj_dir}/{t._dir} {t.proj_dir}/{t._dir}/fastqc_general_stats'
    gc_plot: '{t._R} {t._script}
              --gc_dir {t.proj_dir}/{t._dir}
              --sample_inf {t.sample_inf}'
    reads_quality_plot: '{t._R} {t._script} {t.proj_dir}/{t._dir} {t.sample_inf}'
  star_mapping:
    run_star: 'mkdir -p {t.proj_dir}/{t._mapping_dir}/{t.sample}/ |
               {t._star} --genomeDir {t.star_index}
                         --readFilesIn {t.clean_dir}/{t.sample}_1.{t.fq_suffix} {t.clean_dir}/{t.sample}_2.{t.fq_suffix}
                         --readFilesCommand zcat
                         --outFileNamePrefix {t.proj_dir}/{t._mapping_dir}/{t.sample}/
                         --runThreadN {t._thread}
                         --outSAMtype BAM SortedByCoordinate
                         --outSAMstrandField intronMotif
                         --outFilterType BySJout
                         --outFilterMultimapNmax 20
                         --alignSJoverhangMin 8
                         --alignSJDBoverhangMin 1
                         --outFilterMismatchNmax 999
                         --alignIntronMin 20
                         --alignIntronMax 1000000
                         --alignMatesGapMax 1000000'
    get_bam_file: 'ln -s {t.proj_dir}/{t._mapping_dir}/{t.sample}/Aligned.sortedByCoord.out.bam {t.proj_dir}/{t._bam_dir}/{t.sample}.bam |
                   samtools index {t.proj_dir}/{t._bam_dir}/{t.sample}.bam'
    star_mapping_summary: 'python {t._stats_script} {t.sample_inf} {t.proj_dir}/{t._mapping_dir} {t.proj_dir}/{t._main_dir}/mapping_stats |
                           {t._R} {t._plot_script} --sample_inf {t.sample_inf} --mapping_stats {t.proj_dir}/{t._main_dir}/mapping_stats.plot --out_dir {t.proj_dir}/{t._main_dir}'
  assembly:
    assembly_stringtie_a: '{t._stringtie}
                           {t.gtf}
                           -p {t.thread}
                           -o {t.proj_dir}/{t.assemble_dir}/{t.sample}.gtf
                           {t.bam_dir}/{t.sample}.bam'
    assembly_stringtie_m: '{t._stringtie} --merge
                           {t.gtf}
                           -o {t.proj_dir}/{t.merge_dir}/{t.merge_gtf}
                           {t.proj_dir}/{t.assemble_dir}/gtf.list'
    assembly_quant_prepare: '{t._gffread}
                             {t.proj_dir}/{t.merge_dir}/{t.merge_gtf}
                             -g {t.genome_fa}
                             -w {t.proj_dir}/{t.merge_dir}/{t.merge_fa} |
                             python {t._gene_tr_map_py}
                             --gff {t.proj_dir}/{t.merge_dir}/{t.merge_gtf}
                             --out_dir {t.proj_dir}/{t.merge_dir}/ |
                             {t._kallisto} index
                             -i {t.proj_dir}/{t.merge_dir}/{t.merge_fa}.kallisto_idx
                             {t.proj_dir}/{t.merge_dir}/{t.merge_fa}'
  quant:
    run_kallisto: '{t._kallisto} quant
                  -i {t.tr_index}
                  --bootstrap-samples=100
                  --output-dir {t.proj_dir}/{t.kallisto_dir}/{t.sample}
                  {t.clean_dir}/{t.sample}_1.{t.fq_suffix}
                  {t.clean_dir}/{t.sample}_2.{t.fq_suffix}'
    kallisto_to_matrix: '{t._R} {t._kallisto_to_table_r}
                         --kallisto_dir {t.proj_dir}/{t.kallisto_dir}
                         --sample_inf {t.sample_inf}
                         --gene2tr {t.gene2tr}
                         --out_dir {t.proj_dir}/{t.exp_dir}'
    run_diff: '{t._R} {t._diff_analysis_r}
               --kallisto_dir {t.proj_dir}/{t.kallisto_dir}
               --tpm_table {t.proj_dir}/{t.exp_dir}/Gene.tpm.txt
               --compare {t.compare}
               --sample_inf {t.sample_inf}
               --gene2tr {t.gene2tr}
               --out_dir {t.proj_dir}/{t.diff_dir}/{t.compare}
               --qvalue {t.qvalue}
               --logfc {t.logfc}'
    quant_report_data: '{t._R} {t._quant_report_r}
                        --exp_dir {t.proj_dir}/{t.exp_dir}
                        --diff_dir {t.proj_dir}/{t.diff_dir}
                        --sample_inf {t.sample_inf}
                        --qvalue {t.qvalue}
                        --logfc {t.logfc}'
  quick_enrich:
    run_goseq: '{t._R} {t._run_goseq_script}
                --name {t.name}
                --gene_list {t.genes}
                --go_anno {t.go}
                --topgo_anno {t.topgo}
                --gene_length {t.gene_length}
                --out_dir {t.proj_dir}/{t._go_dir}/{t.name} |
                {t._R} {t._plot_enrich}
                --enrich_table {t.proj_dir}/{t._go_dir}/{t.name}/{t.name}.go.enrichment.txt'
    run_kobas: 'python {t._extract_inf_py}
                --id {t.genes}
                --table {t.kegg}
                --output {t.proj_dir}/{t._blast_dir}/{t.name}.blasttab |
                mkdir -p {t.proj_dir}/{t._kegg_dir}/{t.name} |
                run_kobas.py
                -i {t.proj_dir}/{t._blast_dir}/{t.name}.blasttab
                -t blastout:tab
                -s {t.sp}
                -b {t.kegg_bg}
                -d K
                -o {t.proj_dir}/{t._kegg_dir}/{t.name}/{t.name}.kegg.enrichment.txt |
                python {t._treat_table_py}
                -k {t.proj_dir}/{t._kegg_dir}/{t.name}/{t.name}.kegg.enrichment.txt |
                {t._R} {t._plot_enrich}
                --enrich_table {t.proj_dir}/{t._kegg_dir}/{t.name}/{t.name}.kegg.enrichment.txt'
    run_pathway: 'mkdir -p {t.proj_dir}/{t._kegg_dir}/{t.name}/pathway |
                  python {t._pathway_py}
                  --kegg_table {t.proj_dir}/{t._kegg_dir}/{t.name}/{t.name}.kegg.enrichment.txt
                  --blast_out {t.proj_dir}/{t._blast_dir}/{t.name}.blasttab
                  --species {t.sp}
                  --out_dir {t.proj_dir}/{t._kegg_dir}/{t.name}/pathway'
  enrich:
    run_goseq: '{t._R} {t._run_goseq_script}
                --name {t.compare}.{t.reg}
                --gene_list {t.genes}
                --go_anno {t.go}
                --topgo_anno {t.topgo}
                --gene_length {t.gene_length}
                --out_dir {t.proj_dir}/{t.go_dir}/{t.compare}'
    run_kobas: 'python {t._extract_inf_py}
                --id {t.genes}
                --table {t.kegg}
                --output {t.proj_dir}/{t.blast_dir}/{t.compare}.{t.reg}.blasttab |
                mkdir -p {t.proj_dir}/{t.kegg_dir}/{t.compare} |
                run_kobas.py
                -i {t.proj_dir}/{t.blast_dir}/{t.compare}.{t.reg}.blasttab
                -t blastout:tab
                -s {t.sp}
                -b {t.kegg_bg}
                -d K
                -o {t.proj_dir}/{t.kegg_dir}/{t.compare}/{t.compare}.{t.reg}.kegg.enrichment.txt |
                python {t._treat_table_py}
                -k {t.proj_dir}/{t.kegg_dir}/{t.compare}/{t.compare}.{t.reg}.kegg.enrichment.txt'
    run_pathway : 'mkdir -p {t.proj_dir}/{t.kegg_dir}/{t.compare}/{t.compare}.{t.reg}.pathway |
                   python {t._pathway_py}
                   --kegg_table {t.proj_dir}/{t.kegg_dir}/{t.compare}/{t.compare}.{t.reg}.kegg.enrichment.txt
                   --blast_out {t.proj_dir}/{t.blast_dir}/{t.compare}.{t.reg}.blasttab
                   --species {t.sp}
                   --out_dir {t.proj_dir}/{t.kegg_dir}/{t.compare}/{t.compare}.{t.reg}.pathway
                   --diff_out {t.proj_dir}/{t.diff_dir}/{t.compare}/{t.compare}.{t.diff_sfx}'
    run_enrich_barplot: '{t._R} {t._enrich_plot}
                         --anno {t.go}
                         --table {t.proj_dir}/{t.go_dir}/{t.compare}/
                         --diff {t.proj_dir}/{t.diff_dir}/{t.compare}/
                         --type go |
                         {t._R} {t._enrich_plot}
                         --anno {t.kegg}
                         --table {t.proj_dir}/{t.kegg_dir}/{t.compare}/
                         --diff {t.proj_dir}/{t.diff_dir}/{t.compare}/
                         --type kegg'
  _module_summary:
    pipe_report: 'echo "prepare report"'
  cp_results: 'rsync
               -av
               --copy-links
               --exclude-from={t.proj_dir}/{t.main_dir}/.ignore
               {t.proj_dir}/{t.main_dir}
               {t.proj_dir}/{t.result_dir} |
               rsync
               -av
               --files-from={t.proj_dir}/{t.main_dir}/.report_files
               {t.proj_dir}/{t.main_dir}
               {t.proj_dir}/{t.report_data}/{t.main_dir}'

#################################################
# files ignore in results and needed in report  #
#################################################

pipe_cmd: '_module_summary pipe_all
           --proj-dir {t.proj_dir}
           --sample-inf {t.sample_inf}
           --clean-dir {t.fq_dir}
           --run-modules {t.module}
           --species {t.latin_name}
           --database {t.database}
           --workers {t.workers}
           --database-version {t.database_version}
           --kegg-bg {t.kegg_bg}'



#################################################
# files ignore in results and needed in report  #
#################################################
module_file:
  fastqc:
    ignore_files:
      - '.ignore'
      - 'logs'
      - 'fastqc_results/*zip'
      - '.report_files'
    pdf_files:
      - 'fastqc_general_stats.txt'
      - 'gc_plot/*gc_distribution.line.png'
      - 'reads_quality_plot/*reads_quality.bar.png'
  star_mapping:
    ignore_files:
      - '.ignore'
      - 'logs'
      - 'mapping_dir'
      - 'bam_dir'
      - 'mapping_stats.plot'
      - 'Rplots.pdf'
      - 'mapping_stats.report'
      - '.report_files'
    pdf_files:
      - 'mapping_stats_plot.png'
      - 'mapping_stats.report'
      - 'mapping_stats.txt'
  quant:
    ignore_files:
      - '.ignore'
      - 'logs'
      - 'kallisto/*/run_info.json'
      - '.report_files'
      - 'Rplots.pdf'
      - 'expression_summary/pdf.*'
      - 'expression_summary/html.*'
      - 'expression_summary/ALL.Volcano_plot.p*'
    pdf_files:
      - 'expression_summary/*.png'
      - 'differential_analysis/*/*png'
      - 'expression_summary/*Gene.tpm.txt'
      - 'expression_summary/*example.diff.table.txt'
      - 'differential_analysis/*/*.edgeR.DE_results.txt'
  enrich:
    ignore_files:
      - '.ignore'
      - 'logs'
      - 'blasttab'
      - '.report_files'
      - 'report.go.table.txt'
      - 'report.kegg.table.txt'
      - 'CC.GO.DAG.png'
      - 'MF.GO.DAG.png'
      - 'BP.GO.DAG.png'
      - 'go.enrichment.barplot.png'
      - 'kegg.enrichment.barplot.png'
      - 'kegg.pathview.png'
    pdf_files:
      - 'go/*/*go.enrichment.barplot.png'
      - 'kegg/*/*kegg.enrichment.barplot.png'
      - 'go/*/DAG/ALL*png'
      - 'go/*/*.ALL.go.enrichment.txt'
      - 'kegg/*/*ALL.kegg.enrichment.txt'
      - 'report.go.table.txt'
      - 'report.kegg.table.txt'
      - 'CC.GO.DAG.png'
      - 'MF.GO.DAG.png'
      - 'BP.GO.DAG.png'
      - 'go.enrichment.barplot.png'
      - 'kegg.enrichment.barplot.png'
      - 'kegg.pathview.png'
  quick_enrich:
    ignore_files:
      - '.ignore'
      - 'logs'
      - 'Rplots.pdf'
      - '.report_files'
      - 'blasttab'


#################################################
# file names                                    #
#################################################
file_suffix:
  fq: 'clean.fq.gz'
  diff_list: 'edgeR.DE_results.diffgenes.txt'
  diff_table: 'edgeR.DE_results.txt'
  assembly:
    merge_gtf: 'merged.gtf'
    merge_fa: 'merged.fa'
    gene_tr_map: 'gene_trans.map'


#################################################
# report pictures                               #
#################################################

report_picture:
  path:
    reads_quality_plot: 'fastqc/reads_quality_plot/reads_quality.bar.png'
    gc_plot: 'fastqc/gc_plot/gc_distribution.line.png'
    mapping_plot: 'mapping/mapping_stats_plot.png'
    inner_dis_plot: 'rseqc/inner_distance/inner_distance.bar.png'
    genebody_cov_plot: 'rseqc/genebody_coverage/genebody_coverage.point.png'
    reads_dis_plot: 'rseqc/read_distribution/read_distribution.bar.png'
    sample_cor_plot: 'quantification/expression_summary/Sample.correlation.heatmap.png'
    exp_dis_plot: 'quantification/expression_summary/Gene_expression.png'
    volcano_plot: 'quantification/expression_summary/ALL.Volcano_plot.png'
    diff_heatmap: 'quantification/expression_summary/Diff.genes.heatmap.png'
    diff_cluster: 'quantification/expression_summary/Diff.genes.cluster.png'
    go_bar_plot: 'enrichment/go.enrichment.barplot.png'
    kegg_bar_plot: 'enrichment/kegg.enrichment.barplot.png'
  size:
    reads_quality_plot: '3000,2500'
    gc_plot: '3000,2500'
    mapping_plot: '2280,2040'
    inner_dis_plot: '3600,3000'
    genebody_cov_plot: '3000,2100'
    reads_dis_plot: '2760,2720'
    sample_cor_plot: '2760,2460'
    exp_dis_plot: '1920,3000'
    volcano_plot: '2600,3000'
    diff_heatmap: '2000,2400'
    diff_cluster: '2000,2400'
    go_bar_plot: '2325,1890'
    kegg_bar_plot: '2325,1890'


#################################################
# databases                                     #
#################################################
database:
  genome: '/public/database/genome/'
  kegg_pathway: ''
